name: Veracode Dynamic Analysis
on: workflow_dispatch
    
jobs:
  static_analysis:
    name: Veracode Dynamic Analysis
    env:
      VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
      VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
      JOB_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest

    
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Initiate Veracode Dynamic Analysis
        run: |
          pip install -r vera-scripts/requirements.txt -q
          echo "Completed Installing Required Dependencies"
          python vera-scripts/create-da-scan.py
